location: ${LOCATION}

server:
  port: 8080

logger:
  level: ${LOGGER_LEVEL}
  disableCaller: false
  disableStacktrace: false
  outputPaths: ['stderr']
  errorOutputPaths: ['stderr']
  encoding: ${LOGGER_ENCODING}
  encoderConfig:
    messageKey: "msg"
    levelKey: "level"
    levelEncoder: ${LOGGER_LEVEL_ENCODER}
    nameKey: "logger"
    timeKey: "ts"
    callerKey: "caller"
    stacktraceKey: "stacktrace"
    timeEncoder: "rfc3339nano"
    durationEncoder: "second"
    callerEncoder: "full"
    nameEncoder: "full"

db:
  dsn: ${DB_DSN}
  max_open_conns: ${DB_MAX_OPEN_CONNS}
  max_idle_conns: ${DB_MAX_IDLE_CONNS}
  conn_max_lifetime: ${DB_CONN_MAX_LIFETIME}   # value in seconds
  debug: ${DB_DEBUG}
